import Head from 'next/head'
import FileUpload from '@/components/FileUpload'
import { useState } from 'react'

export default function Home() {
  const [file, setFile] = useState<File | null>(null);

  const handleFileAdded = (newFile: File) => {
    setFile(newFile);
  };

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <FileUpload onFileAdded={handleFileAdded} />
      {file && <p>File name: {file.name}</p>}
      </main>
    </>
  )
}
