import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import FileUpload from '@/components/FileUpload'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [file, setFile] = useState<File | null>(null);

  const handleFileAdded = (newFile: File) => {
    setFile(newFile);
  };

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <FileUpload onFileAdded={handleFileAdded} />
      </main>
    </>
  )
}
